### PR TITLE
Feature/rework vwtest output

### PR DESCRIPTION
**Pull request by ivan-pavlov**
So, finally over
This PR adds new features:
- Multi-column predictions output for `vwtest` using `full_probs = T` argument.
- Possibility to specify parameters directly like in CL version
```
vwsetup(
    params_str = "--random_seed 1 --quadratic bc --learning_rate 0.05 --l1 1E-7 --ect 3"
)
```

Also:
- More tests to get codecov of around 90%
- New demo and reworked documentation (types and defaults are specified for all parameters)
- Bunch of bug fixes

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Solid work -- inspected, built, tested, installed, ran demos.

Looks ready to me!

**Review by eddelbuettel — APPROVED** [review]

**Comment by eddelbuettel** [comment]
I'd say feel free to merge unless you are waiting on @coatless ...

**Comment by ivan-pavlov** [comment]
@coatless , I would be happy to see your review, but if you are busy right now, then I guess one approval is enough

**Comment by coatless** [comment]
Hi folks, I was traveling. I'll review this after I finish lecturing for the day ~4pm CDT.

**Review by coatless — APPROVED** [review]
Looks great! I'm impressed with the new demos...

**Pull request merged**
